### ISSUE TITLE
Can't mock include

### ISSUE THREAD

**Issue by piersb** [duncan3dc/uopz-expectations#1]
Steps to reproduce:

Uopz-expectations is working:

    public function test() {
        CoreFunction::mock('time')->andReturn(666);
        echo time();
    }

    This test did not perform any assertions
    666

Call to include fails:

    public function test() {
        //		CoreFunction::mock('include');
        include('some/path');
    }

    include(some/path): failed to open stream: No such file or directory

Mocked call to include also fails

    public function test() {
		CoreFunction::mock('include');
		include('some/path');
    }

    ReflectionException : Function include() does not exist
         /vendor/duncan3dc/uopz-expectations/src/ClosureGenerator.php:79
         /vendor/duncan3dc/uopz-expectations/src/ClosureGenerator.php:31
         /vendor/duncan3dc/uopz-expectations/src/CoreFunction.php:33

**Comment by duncan3dc** [comment]
Hi @piersb,

The [include](http://php.net/manual/en/function.include.php) statement in PHP is not a function, so you cannot mock it using uopz unfortunately
